name: Lights
version: 0.4.5
description: Make arrays of glowstone lights that can be switched on and off using stone buttons.
author: Delphi-Dev
main: delphi.net.lights.Lights
commands:
    lcreate:
        description: Make a new light array
        usage: /lcreate <name>
    ladd:
        desctiption: Adds a light to an array
        usage: /ladd while targeting a block to use as a light
    lswadd:
        description: Adds a switch to the array
        usage: /lswadd while targeting a block to use as a switch
    lplacemode:
        description: Enables /disables placemode
        usage: /lplacemode
    lfinish:
        description: Finish making an array
        usage: /lfinish
    lon:
        description: Turns the lights in an array on
        usage: /lon <name>
    loff:
        description: Turns the lights in an array off
        usage: /loff <name>
    ledit:
        description: Edit an existing array
        usage: /ledit <name>
    llist:
        description: List arrays that exist
        usage: /llist